version: 0.0
os: linux
files:
  - source: target/DevOpsSummative-1.0-SNAPSHOT.jar
    destination: /home/ec2-user/app
  - source: scripts/deploy.sh
    destination: /home/ec2-user/scripts

permissions:
  - object: /home/ec2-user/app/DevOpsSummative-1.0-SNAPSHOT.jar
    owner: ec2-user
    mode: 755
  - object: /home/ec2-user/scripts/deploy.sh
    owner: ec2-user
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
