version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Build started on `date`
  build:
    commands:
      - echo Building the project...
      - mvn clean package
      - mvn test || { echo "Unit tests failed! Stopping pipeline."; exit 1; }
      - chmod +x scripts/deploy.sh

artifacts:
  files:
    - appspec.yml
    - target/DevOpsSummative-1.0-SNAPSHOT.jar
    - scripts/deploy.sh
  reports:
    java-test-report:
      files:
        - '**/TEST-*.xml'